env:
  node: true
  jest: true

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaVersion: 2020
  sourceType: module
  project: tsconfig.json

plugins:
  - '@typescript-eslint'
  - jest
  - prefer-arrow
  - import

extends:
  - eslint:recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - airbnb-base
  - airbnb-typescript/base
  - plugin:jest/recommended
  - plugin:jest/style
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - prettier # must go last, to turn off some previous rules

rules:
  no-plusplus: off
  no-console: off
  no-restricted-syntax: off
  prefer-arrow-callback: error
  prefer-arrow/prefer-arrow-functions: error
  arrow-body-style: off
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
        - '**/*test*'
  import/extensions: off
  import/prefer-default-export: off
  import/no-cycle: off
  no-unused-vars: off
  '@typescript-eslint/no-unused-vars': error
  jest/valid-title: off
  jest/no-commented-out-tests: off
  jest/no-focused-tests: warn
  jest/expect-expect: off
